### ISSUE TITLE
Crash : when join server - getCurrentSeason()

### ISSUE THREAD

**Issue by AngleNaris** [lucaargolo/fabric-seasons#124]
`java.lang.NoSuchMethodError: 'io.github.lucaargolo.seasons.utils.Season io.github.lucaargolo.seasons.FabricSeasons.getCurrentSeason()'
	at io.github.lucaargolo.seasons.FabricSeasons.getTimeToNextSeason(FabricSeasons.java:172)
	at io.github.lucaargolo.seasonsextras.block.SeasonCalendarBlock.updateState(SeasonCalendarBlock.java:79)
	at io.github.lucaargolo.seasonsextras.blockentities.SeasonCalendarBlockEntity.serverTick(SeasonCalendarBlockEntity.java:21)
	at MC//net.minecraft.world.chunk.WorldChunk$DirectBlockEntityTickInvoker.tick(WorldChunk.java:660)
	at MC//net.minecraft.world.chunk.WorldChunk$WrappedBlockEntityTickInvoker.tick(WorldChunk.java:714)
	at MC//net.minecraft.world.World.redirect$fen000$observable$redirectTick(World.java:9567)
	at MC//net.minecraft.world.World.tickBlockEntities(World.java:456)
	at MC//net.minecraft.server.world.ServerWorld.tick(ServerWorld.java:376)
	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer.java:875)
	at MC//net.minecraft.server.dedicated.MinecraftDedicatedServer.tickWorlds(MinecraftDedicatedServer.java:289)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:819)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base@17.0.7/java.lang.Thread.run(Thread.java:833)`

Full crash log is in [here](https://crashy.net/b188a3be-2395-412d-bf19-f8d4f524fca4).

**Comment by whatamaniac** [comment]
Same crash but it happened when i try to place Calender on wall. Crashes everytime when tried to place Season Calender. Lemme know if you need my logs or crash reports.

**Comment by lucaargolo** [comment]
That's a weird crash. Apparently, you're using the latest releases, but I can't reproduce it on my machine. Tested all the latest files for 1.19.2, 1.19.3, and 1.19.4 and the calendar worked on all versions. Are you sure you downloaded all the latest files in CurseForge or Modrinth?

**Comment by whatamaniac** [comment]
Yes i am using the latest version of Fabric Seasons (fabric-seasons-2.2+1.19.jar) and Fabric Seasons Extras (fabric-seasons-extras-1.2-BETA+1.19.jar). Happens when i try placing Season Calender... Here's the Crash Report: https://pastebin.com/8SZF2EdH
Here's a recording: https://www.veed.io/view/03f4aee7-5fa2-4f69-a889-e256dcf6f650?panel=share

**Comment by Fisch37** [comment]
I get the same exact crash on my server. On client it works fine. First I tried v2.2, but after testing it seems 2.1 has the crash as well. 
**However**: The crash only occured for me when using the `/session query` command from the server's console. If I used the command system on client, it didn't respond with anything. I don't have Season Extras, only the Terralith compat which is on the recent version. (Though I don't see that as being a connecting factor.)

This discreptancy could explain why @lucaargolo wasn't able to reproduce the crash, maybe they were in a Singleplayer world. 
[Crash Report](https://pastebin.com/27EnLcFS)

**Comment by Calmingstorm** [comment]
Can confirm, when running this via console the same crash occurs - running as an OP in game, no response.

`Time: 2023-05-30 11:09:40
Description: Exception in server tick loop

java.lang.NoSuchMethodError: 'io.github.lucaargolo.seasons.utils.Season io.github.lucaargolo.seasons.FabricSeasons.getCurrentSeason()'
	at io.github.lucaargolo.seasons.FabricSeasons.getTimeToNextSeason(FabricSeasons.java:170)
	at io.github.lucaargolo.seasons.commands.SeasonCommand.lambda$register$5(SeasonCommand.java:36)
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:263)
	at MC//net.minecraft.server.command.CommandManager.redirect$zho000$architectury$performCommand(CommandManager.java:1045)
	at MC//net.minecraft.server.command.CommandManager.execute(CommandManager.java:271)
	at MC//net.minecraft.server.command.CommandManager.executeWithPrefix(CommandManager.java:264)
	at MC//net.minecraft.server.dedicated.MinecraftDedicatedServer.executeQueuedCommands(MinecraftDedicatedServer.java:305)
	at MC//net.minecraft.server.dedicated.MinecraftDedicatedServer.tickWorlds(MinecraftDedicatedServer.java:290)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:819)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base@18.0.2.1/java.lang.Thread.run(Unknown Source)`
