### ISSUE TITLE
Crashing on Crop Tester

### ISSUE THREAD

**Issue by Kauan-Gama** [lucaargolo/fabric-seasons#170]
I Tried Using the crop Tester But it Crashed my game, i believe it's due to incompatibilities with other mods

Crash Report:
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 2023-11-17 13:34:32
Description: Unexpected error

java.lang.NullPointerException: Cannot read field "field_22789" because "currentScreen" is null
	at net.minecraft.class_332.handler$bmp000$iceberg$preRenderTooltipInternal(class_332.java:1341)
	at net.minecraft.class_332.method_51435(class_332.java)
	at net.minecraft.class_332.method_51447(class_332.java:613)
	at net.minecraft.class_332.method_51434(class_332.java:609)
	at io.github.lucaargolo.seasonsextras.utils.TooltipRenderer.renderTestedBlock(TooltipRenderer.java:54)
	at io.github.lucaargolo.seasonsextras.utils.TooltipRenderer.render(TooltipRenderer.java:31)
	at io.github.lucaargolo.seasonsextras.client.FabricSeasonsExtrasClient.lambda$onInitializeClient$4(FabricSeasonsExtrasClient.java:91)
	at net.fabricmc.fabric.api.client.rendering.v1.HudRenderCallback.lambda$static$0(HudRenderCallback.java:27)
	at net.minecraft.class_329.handler$bhn000$fabric-rendering-v1$render(class_329.java:3386)
	at net.minecraft.class_329.method_1753(class_329.java:370)
	at net.minecraft.class_757.redirect$eag000$vivecraft$noGUIwithViewOnly(class_757.java:7071)
	at net.minecraft.class_757.method_3192(class_757.java:926)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_332.handler$bmp000$iceberg$preRenderTooltipInternal(class_332.java:1341)
	at net.minecraft.class_332.method_51435(class_332.java)
	at net.minecraft.class_332.method_51447(class_332.java:613)
	at net.minecraft.class_332.method_51434(class_332.java:609)
	at io.github.lucaargolo.seasonsextras.utils.TooltipRenderer.renderTestedBlock(TooltipRenderer.java:54)
	at io.github.lucaargolo.seasonsextras.utils.TooltipRenderer.render(TooltipRenderer.java:31)
	at io.github.lucaargolo.seasonsextras.client.FabricSeasonsExtrasClient.lambda$onInitializeClient$4(FabricSeasonsExtrasClient.java:91)
	at net.fabricmc.fabric.api.client.rendering.v1.HudRenderCallback.lambda$static$0(HudRenderCallback.java:27)
	at net.minecraft.class_329.handler$bhn000$fabric-rendering-v1$render(class_329.java:3386)
	at net.minecraft.class_329.method_1753(class_329.java:370)
	at net.minecraft.class_757.redirect$eag000$vivecraft$noGUIwithViewOnly(class_757.java:7071)

-- Affected level --
Details:
	All players: 1 total; [class_746['Kaka_Sama'/372, l='ClientLevel', x=-6.46, y=62.94, z=48.62]]
	Chunk stats: 636, 636
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,69,32), Section: (at 0,5,0 in 0,4,2; chunk contains blocks 0,-64,32 to 15,319,47), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 1584860 game time, 2012545 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:458)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:826)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, tinyskeletons, minecraft:supporteatinganimation

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1341533952 bytes (1279 MiB) / 3489660928 bytes (3328 MiB) up to 3758096384 bytes (3584 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i3-9100F CPU @ 3.60GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 10
	Microarchitecture: Coffee Lake
	Frequency (GHz): 3.60
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 4
	Graphics card #0 name: NVIDIA GeForce GT 1030
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1d01
	Graphics card #0 versionInfo: DriverVersion=31.0.15.3667
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: DDR4
	Virtual memory max (MB): 15807.21
	Virtual memory used (MB): 11875.11
	Swap memory total (MB): 7680.00
	Swap memory used (MB): 252.14
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx3558M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		advancementplaques: Advancement Plaques 1.4.11
		adventurez: AdventureZ 1.4.18
		ambientsounds: AmbientSounds 5.2.20
		amplified_nether: Amplified Nether 1.2.2
		appleskin: AppleSkin 2.5.0+mc1.20
		auditory: Auditory 0.0.6-1.20.1
		autotag-convention: AutoTag Convention 2.0.2+1.20
			autotag: AutoTag 2.0.2+1.20
		bedspreads: Bedspreads 6.2.0+1.20.1
		betteradvancements: Better Advancements 0.3.2.161
		betterthirdperson: Better Third Person 1.9.0
		blur: Blur (Fabric) 3.1.0
			midnightlib: MidnightLib 1.4.1
			satin: Satin 1.13.0
		cameraoverhaul: Camera Overhaul 1.4.0-fabric-universal
		camerautils: Camera Utils 1.20.1-1.0.4
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.36+fb8d95da82
		cavedust: Cave Dust 1.4.1
			kirin: Kirin UI 1.15.0
		cherishedworlds: Cherished Worlds 6.1.0+1.20.1
		cloth-config: Cloth Config v11 11.1.106
			cloth-basic-math: cloth-basic-math 0.6.1
		collective: Collective 6.62
		connectiblechains: Connectible Chains 2.2.1+1.20.1
		continuity: Continuity 3.0.0-beta.2+1.20
		creativecore: CreativeCore 2.10.24
			net_minecraftforge_eventbus: eventbus 6.0.3
		dataloader: Data loader 1.1.3+1.19.4-1.20-pre5
		diagonalfences: Diagonal Fences 8.0.0
		disable_custom_worlds_advice: Disable Custom Worlds Advice 4.1
		easyanvils: Easy Anvils 8.0.0
		easymagic: Easy Magic 8.0.0
		eatinganimationid: Eating Animation 1.9.4+1.20
		enhancedvisuals: EnhancedVisuals 1.6.7
		entity_model_features: Entity Model Features 0.2.13
		entity_texture_features: Entity Texture Features 4.4.4
			org_apache_httpcomponents_httpmime: httpmime 4.5.10
		entityculling: EntityCulling-Fabric 1.6.2-mc1.20
		extrasounds: ExtraSounds 2.3.1+1.20.1~lonefelidae16-build.1
			advanced_runtime_resource_pack: Runtime Resource Pack 0.6.7
			soundcategories: Sound Categories 1.2.4+1.20~lonefelidae16-build.1
		fabric-api: Fabric API 0.90.7+1.20.1
			fabric-api-base: Fabric API Base 0.4.30+7abfd51577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.35+4d8536c977
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.12+215bbe9677
			fabric-block-api-v1: Fabric Block API (v1) 1.0.10+92a0d36777
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.0+92a0d36777
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.40+b3afc78b77
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.1+97bb207577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.33+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.12+b3afc78b77
			fabric-commands-v0: Fabric Commands (v0) 0.2.50+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.63+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.10+57aed33f77
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.4+a1a980da77
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.18+aeb40ebe77
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.3.2+d7b148e077
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.53+8536527b77
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.22+b3afc78b77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.1+e91849a877
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.62+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.39+ae9f657a77
			fabric-item-api-v1: Fabric Item API (v1) 2.1.27+b3afc78b77
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.11+d7b148e077
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.34+df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.21+b3afc78b77
			fabric-loot-api-v2: Fabric Loot API (v2) 1.2.0+96dfa95977
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.44+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.8+d7b148e077
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.49+b3afc78b77
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.2+709a987177
			fabric-models-v0: Fabric Models (v0) 0.4.1+9386d8a777
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.10+eeb8eb3677
			fabric-networking-v0: Fabric Networking (v0) 0.3.50+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.2+4ee0bc6077
			fabric-particles-v1: Fabric Particles (v1) 1.1.1+201a23a077
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.20+b3afc78b77
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.2+4df89eb277
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.0+39a511ba77
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.0+39a511ba77
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.45+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.36+92a0d36777
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.27+b3afc78b77
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.48+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.7+b3afc78b77
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.6+d7b148e077
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.9+132c48c177
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.7+b3afc78b77
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.29+b3afc78b77
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.12+b3afc78b77
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.2+1bc31aeb77
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.0+6c31357e77
		fabricloader: Fabric Loader 0.14.24
		fallingleaves: Falling Leaves 1.15.1+1.20.1
		farsight: Farsight Mod 1.20.1-3.7
			org_jctools_jctools-core: jctools-core 4.0.1
		firstperson: FirstpersonModel 2.2.3
		forgeconfigapiport: Forge Config API Port 8.0.0
		herdspanic: Herds Panic 1.0.7
		iceberg: Iceberg 1.1.11
		incendium: Incendium 5.3.0
		indium: Indium 1.0.20+mc1.20.1
		invmove: InvMove 0.8.4
		iris: Iris 1.6.4
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		jamlib: JamLib 0.6.0+1.20
		java: OpenJDK 64-Bit Server VM 17
		lambdynlights: LambDynamicLights 2.3.2+1.20.1
			pride: Pride Lib 1.2.0+1.19.4
			spruceui: SpruceUI 5.0.0+1.20
		lazydfu: LazyDFU 0.1.3
		legendarytooltips: Legendary Tooltips 1.4.4
		libz: LibZ 1.0.1
		lithium: Lithium 0.11.2
		minecraft: Minecraft 1.20.1
		modmenu: Mod Menu 7.1.0
		morebannerfeatures: More Banner Features 1.2.0
		moremobvariants: More Mob Variants 1.2.2
		mousewheelie: Mouse Wheelie 1.11.1+mc1.20-pre2
			amecsapi: Amecs API 1.4.0+mc1.20-pre1
			coat: Coat 1.0.0-beta.20+mc1.20-pre1
			tweed4_annotated: tweed4_annotated 1.3.1+mc1.20-pre1
			tweed4_base: tweed4_base 1.7.1+mc1.20-pre1
			tweed4_data: tweed4_data 1.2.1+mc1.20-pre1
			tweed4_data_hjson: tweed4_data_hjson 1.1.1+mc1.20-pre1
			tweed4_tailor_coat: tweed4_tailor_coat 1.1.3+mc1.20-pre1
			tweed4_tailor_lang_json_descriptions: tweed4_tailor_lang_json_descriptions 1.1.0+mc1.20-pre1
			tweed4_tailor_screen: tweed4_tailor_screen 1.1.4+mc1.20-pre1
		notenoughanimations: NotEnoughAnimations 1.6.4
		nullscape: Nullscape 1.2.1
		presencefootsteps: Presence Footsteps 1.9.0
		prism: Prism 1.0.5
		puzzleslib: Puzzles Lib 8.0.7
		repurposed_structures: Repurposed Structures 7.0.0+1.20-fabric
			com_github_llamalad7_mixinextras: MixinExtras 0.2.0-beta.7
		rightclickharvest: Right Click Harvest 3.2.2+1.19.x-1.20.1-fabric
		seasons: Fabric Seasons 2.2.1+1.20
		seasonsextras: Fabric Seasons: Extras 1.2-BETA+1.20
		shulkerboxtooltip: Shulker Box Tooltip 4.0.4+1.20.1
		sodium: Sodium 0.4.10+build.27
		soulfired: Soul fire'd 3.2.0.0
		sound_physics_remastered: Sound Physics Remastered 1.20.1-1.1.1
		structory: Structory 1.3.2
		terralith: Terralith 2.4.3
		tiered: Tiered 1.2.7
		tinyskeletons: Tiny Skeletons 8.0.0
		tlskincape: TLSkinCape 1.32
		trade_cycling: Trade Cycling 1.20.1-1.0.5
		umu_backpack: UMU Backpack 5.1
			mm: Manningham Mills 2.3
			umu_config: UMU Config 0.0-beta.0
		universalbonemeal: Universal Bone Meal 8.0.0
		vanillatweaks: VanillaTweaks 1.5.69
		veindigging: VeinDigging 1.0.1
		villagernames: Villager Names 5.2
		visuality: Visuality 0.7.0+1.20
		vivecraft: Vivecraft 1.20.1-0.0.15-hotswitch-a5
			org_lwjgl_lwjgl-openvr: lwjgl-openvr 3.3.1
			org_lwjgl_lwjgl-openvr_natives-linux: lwjgl-openvr 3.3.1
			org_lwjgl_lwjgl-openvr_natives-macos: lwjgl-openvr 3.3.1
			org_lwjgl_lwjgl-openvr_natives-windows: lwjgl-openvr 3.3.1
		wakes: Wakes 0.1.6
			blue_endless_jankson: jankson 1.2.2
		xaerominimap: Xaero's Minimap 23.8.4
	Loaded Shaderpack: (off)
	NEC status: No NEC detected
	Launched Version: Better Adventures +
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce GT 1030/PCIe/SSE2 GL version 3.2.0 NVIDIA 536.67, NVIDIA Corporation
	Window size: 1360x768
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, fabric, tinyskeletons, minecraft:supporteatinganimation
	Current Language: pt
	CPU: 4x Intel(R) Core(TM) i3-9100F CPU @ 3.60GHz
	Server Running: true
	Player Count: 1 / 8; [class_3222['Kaka_Sama'/372, l='ServerLevel[Cavalo]', x=-6.46, y=62.94, z=48.62]]
	Data Packs: vanilla, fabric, file/BlazeandCaves Advancements Pack 1.16.1 (1).zip, file/New-Desert-Temple.zip (incompatible), file/New-End-Cities.zip (incompatible), file/New-Ocean-Ruins.zip (incompatible), file/New-Ruined-Portals.zip (incompatible), file/timber v2.1.6 (MC 1.20.x).zip, file/vanillarefresh-v1.4.16d.zip
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Experimental

**Comment by RemagOfficial** [comment]
why do you think its an incompatibility with another mod? it doesnt mention any other mods in the log

**Comment by Kauan-Gama** [comment]
> why do you think its an incompatibility with another mod? it doesnt mention any other mods in the log

My Launcher pointed it as possible cause

**Comment by enso-x** [comment]
Legendary tooltips and Iceberg rewrite drawTooptip methods. IDK how to fix that.

**Comment by RemagOfficial** [comment]
> Legendary tooltips and Iceberg rewrite drawTooptip methods. IDK how to fix that.

why are you coming here for that then?
