### ISSUE TITLE
Tesselation crash

### ISSUE THREAD

**Issue by Furbygeddon** [lucaargolo/fabric-seasons#4]
Starting summer the game crashes with this:

---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 11/16/20 1:03 PM
Description: Tesselating block model

java.lang.IllegalArgumentException: Color parameter outside of expected range: Blue
	at java.awt.Color.testColorValueRange(Color.java:310)
	at java.awt.Color.<init>(Color.java:395)
	at java.awt.Color.<init>(Color.java:369)
	at java.awt.Color.<init>(Color.java:461)
	at io.github.lucaargolo.seasons.utils.ColorHelper.changeSaturation(ColorHelper.java:16)
	at io.github.lucaargolo.seasons.utils.ColorHelper.changeHueSatBri(ColorHelper.java:20)
	at io.github.lucaargolo.seasons.utils.ModConfig.getSeasonGrassColor(ModConfig.java:169)
	at net.minecraft.class_1959.redirect$zom000$getSeasonGrassColor(class_1959.java:736)
	at net.minecraft.class_1959.method_8711(class_1959.java:393)
	at net.minecraft.class_1163$$Lambda$5129/632306280.getColor(Unknown Source)
	at net.minecraft.class_638.method_23780(class_638.java:788)
	at net.minecraft.class_638.method_23781(class_638.java:770)
	at net.minecraft.class_638$$Lambda$5677/2093477133.getAsInt(Unknown Source)
	at net.minecraft.class_4700.method_23770(class_4700.java:43)
	at net.minecraft.class_638.method_23752(class_638.java:770)
	at net.minecraft.class_853.method_23752(class_853.java:137)
	at net.minecraft.class_1163.method_4965(class_1163.java:14)
	at net.minecraft.class_1163.method_4962(class_1163.java:18)
	at net.minecraft.class_324.md4a4957$lambda$create$1$9(class_324.java:1030)
	at net.minecraft.class_324$$Lambda$4127/1780517518.getColor(Unknown Source)
	at net.minecraft.class_324.method_1697(class_324.java:112)
	at net.minecraft.class_778.method_23073(class_778.java:141)
	at net.minecraft.class_778.method_3363(class_778.java:127)
	at net.minecraft.class_778.method_3361(class_778.java:76)
	at net.minecraft.class_778.method_3374(class_778.java:47)
	at net.minecraft.class_776.method_3355(class_776.java:61)
	at net.minecraft.class_846$class_851$class_4578.redirect$zbp000$hookChunkBuildTesselate(class_846.java:715)
	at net.minecraft.class_846$class_851$class_4578.method_22785(class_846.java:512)
	at net.minecraft.class_846$class_851$class_4578.method_22783(class_846.java:434)
	at net.minecraft.class_846.method_22757(class_846.java:136)
	at net.minecraft.class_846$$Lambda$5707/552225831.apply(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952)
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1624)
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

No OptiFine/fabric or anything similar has been used.

**Comment by lucaargolo** [comment]
Oops, sorry about that, I'll fix it asap!.

**Comment by lucaargolo** [comment]
This should be fixed in 1.0.2!
